
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-yaml
    - id: detect-private-key
    - id: pretty-format-json
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: trailing-whitespace


- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    description: Formatting
    args: [--line-length=100]

- repo: https://github.com/pycqa/flake8
  rev: '7.0.0'  # pick a git hash / tag to point to
  hooks:
  - id: flake8
    name: Python linting
    additional_dependencies:
      - flake8-comprehensions
      - flake8-bugbear
    args:
      [--max-line-length=100, "--ignore=E203, W503"]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      args: [--profile=black]

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0  # pick a git hash / tag to point to
  hooks:
  - id: pydocstyle
    name: the annoying one
    args:
    - --ignore=D100, D413, D415, D203, D204, D213, D215, D400, D401, D404, D406, D407, D408, D409

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.10.0'  # Use the sha / tag you want to point at
  hooks:
  - id: mypy
    name: Static type checks
